### 测试登录用户权限获取
GET{{form_host}}/form/test
TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiYXV0aCI6IjkxMDkwIiwic3ViIjoie1widXNlcm5hbWVcIjpcIkFsaWNlXCIsXCJwYXNzd29yZFwiOlwiZTEwYWRjMzk0OWJhNTlhYmJlNTZlMDU3ZjIwZjg4M2VcIn0iLCJpYXQiOjE2Nzk0OTIxNDEsImV4cCI6MTY3OTQ5OTM0MX0.hhtzJR6SMJWsi98wVsJhlw8SRPGSv6XDyYcHw0qSGaq15HBvv9NwuYHtLExo8bGYRnXjO50CPs7GwsSON03GTg

### 发送投诉信息
PUT {{form_host}}/form/complaint
TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiYXV0aCI6IjkwMDkzIiwic3ViIjoie1wiYWlkXCI6MyxcInVzZXJuYW1lXCI6XCJyb3NlXCIsXCJwYXNzd29yZFwiOlwiZTEwYWRjMzk0OWJhNTlhYmJlNTZlMDU3ZjIwZjg4M2VcIixcImF1dGhvcml0eVwiOlwiOTAwOTNcIixcImhpcmVkYXRlXCI6MTY3OTQ5NjA0ODAwMH0iLCJpYXQiOjE2Nzk0OTYxMjcsImV4cCI6MTY3OTUwMzMyN30.bEMpgzvJcWifxomLbnWdotWa2j01pL-pPhAz8ZgZnsH2s3Ik3VH82qRo9BTcpyy7-9Z6jj8IpPv_uWPdSKdtIA
Content-Type: application/json

{
  "title": "测试投诉标题",
  "content": "测试投诉内容"
}

### 前台调用查询投诉信息
GET {{form_host}}/form/complaint/query/1
TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiYXV0aCI6IjkwMDkzIiwic3ViIjoie1wiYWlkXCI6MyxcInVzZXJuYW1lXCI6XCJyb3NlXCIsXCJwYXNzd29yZFwiOlwiZTEwYWRjMzk0OWJhNTlhYmJlNTZlMDU3ZjIwZjg4M2VcIixcImF1dGhvcml0eVwiOlwiOTAwOTNcIixcImhpcmVkYXRlXCI6MTY3OTQ5NjA0ODAwMH0iLCJpYXQiOjE2Nzk0OTYxMjcsImV4cCI6MTY3OTUwMzMyN30.bEMpgzvJcWifxomLbnWdotWa2j01pL-pPhAz8ZgZnsH2s3Ik3VH82qRo9BTcpyy7-9Z6jj8IpPv_uWPdSKdtIA
Content-Type: application/json

{
  "pubilsherId": 1
}

### 删除投诉信息
DELETE {{form_host}}/form/complaint/2
TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MiwiYXV0aCI6IjkwMDkwIiwic3ViIjoie1wiYWlkXCI6MixcInVzZXJuYW1lXCI6XCJNYXJpYXNcIixcInBhc3N3b3JkXCI6XCJjNGQwMzhiNGJlZDA5ZmRiMTQ3MWVmNTFlYzNhMzJjZFwiLFwiYXV0aG9yaXR5XCI6XCI5MDA5MFwiLFwiaGlyZWRhdGVcIjoxNjc5MzMwOTkzMDAwfSIsImlhdCI6MTY3OTQ5NzMzNywiZXhwIjoxNjc5NTA0NTM3fQ.MBs4DzzUQTnZ1De7rLyyzxH5KOp59CTM84rOoAnVWppXuo7TbYzoRvtHXuOvcBDghh_lZ7K9dWBw424FTJd8lA
